### ISSUE TITLE
Debian 7.9  python3.2 (SyntaxError: invalid syntax)

### ISSUE THREAD

**Issue by Busindre** [Plecost/plecost#10]
plecost 
Traceback (most recent call last):
  File "/usr/local/bin/plecost", line 9, in <module>
    load_entry_point('plecost==1.0.4', 'console_scripts', 'plecost')()
  File "/usr/local/lib/python3.2/dist-packages/plecost_lib/plecost.py", line 78, in main
    from .api import run, **version**
  File "/usr/local/lib/python3.2/dist-packages/plecost_lib/api.py", line 46, in <module>
    from .libs.data import PlecostOptions
  File "/usr/local/lib/python3.2/dist-packages/plecost_lib/libs/data.py", line 49, in <module>
    from .utils import get_data_folder
  File "/usr/local/lib/python3.2/dist-packages/plecost_lib/libs/utils.py", line 257
    response = yield from aiohttp.request(
                        ^
SyntaxError: invalid syntax

**Comment by cr0hn** [comment]
You need Python 3.4 or greater to run Plecost. You're running Python 3.2... :)

**Comment by Busindre** [comment]
Thanks, update the documentation would be nice. :+1:

**Comment by cr0hn** [comment]
Doc updated. Thx :)
