### ISSUE TITLE
TypeError: multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by tharbad08** [Plecost/plecost#12]
Traceback (most recent call last):
  File "plecost", line 11, in <module>
    sys.exit(main())
  File "/home/<user>/.local/lib/python3.5/site-packages/plecost_lib/plecost.py", line 78, in main
    from .api import run, **version**
  File "/home/<user>/.local/lib/python3.5/site-packages/plecost_lib/api.py", line 46, in <module>
    from .libs.data import PlecostOptions
  File "/home/<user>/.local/lib/python3.5/site-packages/plecost_lib/libs/data.py", line 49, in <module>
    from .utils import get_data_folder
  File "/home/<user>/.local/lib/python3.5/site-packages/plecost_lib/libs/utils.py", line 41, in <module>
    import aiohttp
  File "/home/<user>/.local/lib/python3.5/site-packages/aiohttp/**init**.py", line 6, in <module>
    from . import hdrs  # noqa
  File "/home/<user>/.local/lib/python3.5/site-packages/aiohttp/hdrs.py", line 2, in <module>
    from .multidict import upstr
  File "/home/<user>/.local/lib/python3.5/site-packages/aiohttp/multidict.py", line 285, in <module>
    class _ItemsView(_ViewBase, abc.ItemsView):
  File "/usr/lib/python3.5/abc.py", line 133, in __new__
    cls = super().**new**(mcls, name, bases, namespace)

Ubuntu 16.04
Python 3.5

I'm not a developer.

**Comment by cr0hn** [comment]
We need more information to fix the issue. How call you Plecost?

**Comment by tharbad08** [comment]
python3.5 plecost

after git clone

**Comment by cr0hn** [comment]
When you run Plecost cloning repo, you must place into the folder _plecost_lib_, and then run Plecost:
`# cd plecost_lib`
`# python plecost.py -h`

How do you run Plecost (The command, not Python version).

**Comment by tharbad08** [comment]
Same. Tried updating CVEs...
Tried with -h too. Same result

**Comment by Aza1337** [comment]
Hi,
Got exactly the same problem

**Comment by cr0hn** [comment]
Oks, identified the bug:

The problem es version of Python. For the moment, Plecost only runs in Python 3.3 and 3.4.

**Comment by dvteam** [comment]
here is a solution (see comments):
https://codeby.net/wordpress/novaja-versija-plecost-1-0-1-programmy-dlja-poiska-ujazvimostej-wordpress/
I applied the suggested solution and everything works ok now

**Comment by cr0hn** [comment]
Plecost ONLY runs in Python 3.4 for the moment

**Comment by dvteam** [comment]
I successfully run it on 3.5 as soon as the fix was applied ;)
