### ISSUE TITLE
Problem with install plecost with python3.5

### ISSUE THREAD

**Issue by dalvarezquiroga** [Plecost/plecost#16]
output:

Traceback (most recent call last):
  File "/usr/local/bin/plecost", line 9, in <module>
    load_entry_point('plecost==1.0.7', 'console_scripts', 'plecost')()
  File "/usr/local/lib/python3.5/dist-packages/plecost-1.0.7-py3.5.egg/plecost_lib/plecost.py", line 78, in main
    from .api import run, __version__
  File "/usr/local/lib/python3.5/dist-packages/plecost-1.0.7-py3.5.egg/plecost_lib/api.py", line 46, in <module>
    from .libs.data import PlecostOptions
  File "/usr/local/lib/python3.5/dist-packages/plecost-1.0.7-py3.5.egg/plecost_lib/libs/data.py", line 49, in <module>
    from .utils import get_data_folder
  File "/usr/local/lib/python3.5/dist-packages/plecost-1.0.7-py3.5.egg/plecost_lib/libs/utils.py", line 41, in <module>
    import aiohttp
  File "/home/dalvarez/.local/lib/python3.5/site-packages/aiohttp/__init__.py", line 6, in <module>
    from . import hdrs  # noqa
  File "/home/dalvarez/.local/lib/python3.5/site-packages/aiohttp/hdrs.py", line 2, in <module>
    from .multidict import upstr
  File "/home/dalvarez/.local/lib/python3.5/site-packages/aiohttp/multidict.py", line 285, in <module>
    class _ItemsView(_ViewBase, abc.ItemsView):
  File "/usr/lib/python3.5/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
TypeError: multiple bases have instance lay-out conflict

**Comment by cr0hn** [comment]
Fixed in release: 1.1.1. Just update:

```bash
python3.5 -m pip install -U plecost
```
