### ISSUE TITLE
multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by d4op** [Plecost/plecost#17]
Traceback (most recent call last):
  File "/usr/local/bin/plecost", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/plecost_lib/plecost.py", line 78, in main
    from .api import run, __version__
  File "/usr/local/lib/python3.5/dist-packages/plecost_lib/api.py", line 46, in <module>
    from .libs.data import PlecostOptions
  File "/usr/local/lib/python3.5/dist-packages/plecost_lib/libs/data.py", line 49, in <module>
    from .utils import get_data_folder
  File "/usr/local/lib/python3.5/dist-packages/plecost_lib/libs/utils.py", line 41, in <module>
    import aiohttp
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from . import hdrs  # noqa
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/hdrs.py", line 2, in <module>
    from .multidict import upstr
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/multidict.py", line 285, in <module>
    class _ItemsView(_ViewBase, abc.ItemsView):
  File "/usr/lib/python3.5/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
TypeError: multiple bases have instance lay-out conflict

**Comment by d4op** [comment]
can be closed.

Fix:
sudo python3 -m pip install --upgrade aiohttp==0.15.3
sudo python3 -m pip install --upgrade beautifulsoup4==4.4.1

gedit /usr/local/lib/python3.5/dist-packages/plecost_lib/libs/utils.py
search: self.q = asyncio.JoinableQueue (loop=self.loop)
replace:  self.q = asyncio.Queue(loop=self.loop)
