### ISSUE TITLE
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden

### ISSUE THREAD

**Issue by dabula-s** [Plecost/plecost#25]
I used your Dockerfile and each start gives the following output:
```
Traceback (most recent call last):
  File "/usr/local/bin/plecost", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/plecost_lib/__main__.py", line 84, in main
    from .api import run, __version__
  File "/usr/local/lib/python3.6/site-packages/plecost_lib/api.py", line 51, in <module>
    from .libs.data import PlecostOptions
  File "/usr/local/lib/python3.6/site-packages/plecost_lib/libs/data.py", line 55, in <module>
    from .utils import get_data_folder
  File "/usr/local/lib/python3.6/site-packages/plecost_lib/libs/utils.py", line 47, in <module>
    import aiohttp
  File "/usr/local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/usr/local/lib/python3.6/site-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/usr/local/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/usr/local/lib/python3.6/site-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/usr/local/lib/python3.6/site-packages/yarl/__init__.py", line 230, in __init_subclass__
    "is forbidden".format(cls))
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
```

**Comment by Hajmer777** [comment]
sudo python3 -m pip install aiohttp==1.3.5 
sudo python3 -m pip install --upgrade beautifulsoup4==4.6.0

**Comment by cr0hn** [comment]
Este issue hace referencia al código legacy de Plecost v1.x/v2.x que ha sido completamente eliminado y reemplazado en v4.0.0. La nueva versión fue reescrita desde cero con Python 3.11+, httpx, Typer y un sistema completamente nuevo. Este problema ya no aplica. Ver rama v3.0.0 para el nuevo código.
