### ISSUE TITLE
plecost --update-cve error

### ISSUE THREAD

**Issue by dabula-s** [Plecost/plecost#26]
```
Traceback (most recent call last):
  File "/usr/local/bin/plecost", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/plecost_lib/__main__.py", line 197, in main
    update_cve(log)
  File "/usr/local/lib/python3.6/site-packages/plecost_lib/libs/updaters/cves.py", line 280, in update_cve
    unzipped_cpe_content = gzip.GzipFile(fileobj=io.BytesIO(cpe_content)).read()
UnboundLocalError: local variable 'cpe_content' referenced before assignment
```

**Comment by kuklofon** [comment]
the same thing...

**Comment by cr0hn** [comment]
Este issue hace referencia al código legacy de Plecost v1.x/v2.x que ha sido completamente eliminado y reemplazado en v4.0.0. La nueva versión fue reescrita desde cero con Python 3.11+, httpx, Typer y un sistema completamente nuevo. Este problema ya no aplica. Ver rama v3.0.0 para el nuevo código.
