### ISSUE TITLE
3.1.1 ?

### ISSUE THREAD

**Issue by d4op** [Plecost/plecost#32]
can you please explain how to get the 3.1.1 ?

if I clone the develop branch it still says 1.1.2 
if I clone the 3.0.0 branch It still says 1.1.2

if I use the develop branch and make install succeed and I launch it --update-plugins I get h2 error for selectors.

so simple question how to get the latest 3.1.1 ?

**Comment by d4op** [comment]
[*] Downloading plugins (slow):  [#] 1.19%Traceback (most recent call last):
  File "/usr/bin/plecost", line 11, in <module>
    load_entry_point('plecost==1.1.2', 'console_scripts', 'plecost')()
  File "/usr/lib/python3/dist-packages/plecost_lib/plecost.py", line 213, in main
    update_plugins(log)
  File "/usr/lib/python3/dist-packages/plecost_lib/libs/updaters/plugins.py", line 114, in update_plugins
    plugin_info = section.xpath(".//h2/a")[0]
IndexError: list index out of range

**Comment by cr0hn** [comment]
Hi @d4op. Current, version 3.1.1 is under development and still there is not An official release because it is not ready, sorry.

**Comment by d4op** [comment]
@cr0hn 
so there is no way to get the 3.3.1 ? or is the develop branch the current 3.1.1. "pre" release code ?

**Comment by cr0hn** [comment]
Este issue hace referencia al código legacy de Plecost v1.x/v2.x que ha sido completamente eliminado y reemplazado en v4.0.0. La nueva versión fue reescrita desde cero con Python 3.11+, httpx, Typer y un sistema completamente nuevo. Este problema ya no aplica. Ver rama v3.0.0 para el nuevo código.
