### ISSUE TITLE
Error al actualizar plugins

### ISSUE THREAD

**Issue by alfonsomoratalla** [Plecost/plecost#5]
$ sudo plecost --update-plugins
[_] Preparing for update plugins...
[_] Downloading plugins (slow):  [###########] 25.00%Traceback (most recent call last):
  File "/usr/local/bin/plecost", line 9, in <module>
    load_entry_point('plecost==1.0.1', 'console_scripts', 'plecost')()
  File "/usr/local/lib/python3.4/dist-packages/plecost_lib/plecost.py", line 191, in main
    update_plugins(log)
  File "/usr/local/lib/python3.4/dist-packages/plecost_lib/libs/updaters/plugins.py", line 111, in update_plugins
    wpage = decode(wpage, detect(wpage)["encoding"])
LookupError: unknown encoding: EUC-TW

**Comment by cr0hn** [comment]
Fixed in commit: a6769710055fda721623b0a8c5c0afef210e75e8
