### ISSUE TITLE
ImportError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by ne0shell** [Plecost/plecost#7]
Traceback (most recent call last):
  File "/usr/local/bin/plecost", line 9, in <module>
    load_entry_point('plecost==1.0.1.post1', 'console_scripts', 'plecost')()
  File "/usr/local/lib/python3.5/site-packages/plecost_lib/plecost.py", line 78, in main
    from .api import run, **version**
  File "/usr/local/lib/python3.5/site-packages/plecost_lib/api.py", line 47, in <module>
    from .libs.versions import find_versions  # noqa
  File "/usr/local/lib/python3.5/site-packages/plecost_lib/libs/versions.py", line 50, in <module>
    from .db import DB
  File "/usr/local/lib/python3.5/site-packages/plecost_lib/libs/db.py", line 37, in <module>
    import sqlite3
  File "/usr/local/lib/python3.5/sqlite3/**init**.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

**Comment by fgeek** [comment]
Not sure which distribution you are running, but please install package libsqlite3-dev or similar.

**Comment by cr0hn** [comment]
You beat me in the response, @fgeek :)
